### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by Lijantropique**
Spanish translation

### CODE REVIEW

**Comment by Lijantropique** [comment]
Hello Bryukh,

One question: what program do you use for the html edition?

I normally use http://www.quackit.com/html/online-html-editor/
but I realize that once I check the final version it deletes all the spaces in the source.
Not a big issue as at the end the result are the same, but it is harder to read the source after that.

Best!

**Comment by Bryukh** [comment]
Pycharm as IDE for python, js and html.
Now I use Atom.

**Comment by Lijantropique** [comment]
Hello Bryukh, 

I tried Atom, but got several issues trying to set up the editor for different versions of python: sometimes I need to run an specific code using python 2.7 and other 3.4. On the other hand, I couldn't add commands args to python scripts using atom (for example, for the AI course on edx, the pacman program requires some arguments).

Best!

**Comment by Bryukh** [comment]
I'm using console to run python in Atom (iterm in tabs) so I don't have this problem )

**Comment by Lijantropique** [comment]
Hello Bryukh, 

I tried it again and now I was able to pass the command arguments. However, still got the issue of specifying which version of python I want to use for a specific program.  BTW, I didn't get the "(iterm in tabs)" part. 

Best!

**Comment by Bryukh** [comment]
I'm using "term2" package and can open a console in atom as in tab. Then I run that I need with python or python3. And for many project I use virtualenv.
2015-05-01 20-36-39 iterm curdir - users bryukh checkio sources missions empire_battle - atom

**Comment by Lijantropique** [comment]
Thanks a lot.
I got some issues installing those packages in Windows (7 and 8.1).
I will try with a Linux.

Best!

**Comment by Bryukh** [comment]
Oh! Windows. Sorry I'm used for MacOS and Linux and forget about Windows :-)

**Comment by Lijantropique** [comment]
Hahahaha :)
I cannot avoid Windows: At my office they set-up everything for me, including the OS. 
At home, for compatibility with my office, I must have Windows as well (but I have set up a dual boot).


Regarding a totally different topic:
Would you be interested in a Hockey AI game?
http://russianaicup.ru/p/packs

Regards,
Oscar J.

**Comment by Bryukh** [comment]
I would, but don't have time for it now. Too much work with our new project.

**Comment by Lijantropique** [comment]
No problem. I will let you know once my bot is ready to play.
Anything I can help you with in the new project?

**Comment by Bryukh** [comment]
Testing and feedback when we will start beta launch.

**Pull request merged**
